language: ruby
sudo: false
before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 2.4.1
  - jruby-1.7.26
  - jruby-9.1.8.0
  - rbx-3.72
matrix:
  allow_failures:
    - rvm: rbx-3.72
os:
  - osx
osx_image: xcode9
